// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyivA9U13AU5LDa0o-xNmbaxtOhcuJ2O8',
    appId: '1:305204923050:web:0e70ad6922b165e7b9ded3',
    messagingSenderId: '305204923050',
    projectId: 'mechaconnect-4e83b',
    authDomain: 'mechaconnect-4e83b.firebaseapp.com',
    storageBucket: 'mechaconnect-4e83b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwRUptjFwtyTo9ON5C3y4urkbZ52volNw',
    appId: '1:305204923050:android:172a1ca44f373338b9ded3',
    messagingSenderId: '305204923050',
    projectId: 'mechaconnect-4e83b',
    storageBucket: 'mechaconnect-4e83b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAiOropZMWbdtXQhSFPJenM9rA6zpgxzI',
    appId: '1:305204923050:ios:41ea606222a697c6b9ded3',
    messagingSenderId: '305204923050',
    projectId: 'mechaconnect-4e83b',
    storageBucket: 'mechaconnect-4e83b.firebasestorage.app',
    iosBundleId: 'com.example.mekaApp',
  );
}
